country_tunes = [
    ['Beer For My Horses','Toby Keith with Willie Nelson'],
    ['I Love You','Martina McBride'],
    ["Walkin' Away",'Clint Black'],
    ["I'm Alright",'Jo Dee Messina'],
    ["Nobody's Home",'Clint Black'],
    ['Remember When','Alan Jackson'],
    ['Roll With Me','Montgomery Gentry'],
    ['Summertime','Kenny Chesney'],
    ['Carrying Your Love With Me','George Stroit'],
    ['Breathe','Faith Hill'],
    ["Don't Rock The Jukebox",'Alan Jackson'],
    ["God Gave Me You",'Blake Shelton'],
    ["Chicken Fried",'The Zac Brown Band'],
    ["Pickup Man",'Joe Diffie'],
    ["Good Morning Beautiful",'Steve Holy'],
    ["Bless the Broken Road",'Rascal Flatts'],
    ["Time Marches On",'Tracy Lawrence'],
    ["Unanswered Prayers",'Garth Brooks'],
    ["Love, Me",'Collin Raye'],
    ["Keep me in mind",'The Zac Brown Band'],
    ["I swear",'John Michael Montgomery'],
    ["Our Song",'Taylor Swift'],
    ["Do I",'Luke Bryan'],
    ["Some Beach",'Blake Shelton'],
    ["Love gets me every time",'Shania Twain'],
    ["Ain't nothing about you",'Brooks and Dunn'],
    ["Wide Open Spaces",'Dixie Chicks'],
    ["Something Like That",'Tim McGraw'],
    ["Chattahoochee",'Alan Jackson'],
    ["Achy Breaky Heart",'Billy Ray Cyrus'],
    ["Consider Me Gone",'Reba'],
    ["I Just Got Started Lovin' You",'James Otto'],
    ["Blue Clear Sky",'George Strait'],
    ["Little Bitty",'Alan Jackson'],
    ["Blown Away",'Carrie Underwood'],
    ["Jesus, take the wheel",'Carrie Underwood'],
    ["One night at a time",'George Strait'],
    ["Don't let our love start slipping away",'Vince Gill'],
    ["The Good Stuff",'Keney Chesney'],
    ["Jukebox in my mind",'Alabama']
]

critical_animals = [
    "Addax",
    "African wild ass",
    "Alabama cavefish",
    "Amur leopard",
    "Arakan forest turtle",
    "Asiatic cheetah",
    "Axolotl",
    "Bactrian camel",
    "Brazilian merganser",
    "Brown spider monkey",
    "California condor",
    "Chinese alligator",
    "Chinese giant salamander",
    "Gharial",
    "Hawaiian monk seal",
    "Iberian lynx",
    "Island fox",
    "Javan rhino",
    "Kakapo",
    "Leatherback sea turtle",
    "Mediterranean monk seal",
    "Mexican wolf",
    "Mountain gorilla",
    "Northern hairy-nosed wombat",
    "Philippine eagle",
    "Red wolf",
    "Saiga",
    "Siamese crocodile",
    "Spix's macaw",
    "Southern bluefin tuna",
    "Sumatran orangutan",
    "Sumatran rhinoceros",
    "Vaquita",
    "Yangtze river dolphin",
    "Northern white rhinoceros",
    "Asiatic Lion",
    "African grey parrot",
    "African elephant",
    "American paddlefish",
    "Common carp",
    "Clouded leopard",
    "Cheetah",
    "Chinese giant salamander",
    "Dugong",
    "Far eastern curlew",
    "Fossa",
    "Galapagos tortoise",
    "Gaur",
    "Blue-eyed cockatoo",
    "Golden hamster",
    "Whale shark",
    "Crowned crane",
    "Hippopotamus",
    "Humboldt penguin",
    "Indian rhinoceros",
    "Komodo dragon",
    "Lesser white-fronted goose",
    "Lion",
    "Mandrill",
    "Maned sloth",
    "Mountain zebra",
    "Polar bear",
    "Red panda",
    "Sloth bear",
    "Takin",
    "Yak",
    "African penguin",
    "African wild dog",
    "Asian elephant",
    "Blue whale",
    "Bonobo",
    "Bornean orangutan",
    "Common chimpanzee",
    "Dhole",
    "Eastern lowland gorilla",
    "Ethiopian wolf",
    "Hispid hare",
    "Giant otter",
    "Giant panda",
    "Goliath frog",
    "Green sea turtle",
    "Grevy's zebra",
    "Hyacinth macaw",
    "Japanese crane",
    "ALear's macaw",
    "Malayan tapir",
    "Markhor",
    "Persian leopard",
    "Proboscis monkey",
    "Pygmy hippopotamus",
    "Red-breasted goose",
    "Rothschild's giraffe",
    "Snow leopard",
    "Steller's sea lion",
    "Scopas tang",
    "Takhi",
    "Tiger",
    "Vietnamese pheasant",
    "Volcano rabbit",
    "Wild water buffalo"
]

extinct_animals = [
    "Atlas bear",
    "Aurochs",
    "Bali tiger",
    "Blackfin cisco",
    "Caribbean monk seal",
    "Carolina parakeet",
    "Caspian tiger",
    "Dodo",
    "Dusky seaside sparrow",
    "Eastern cougar",
    "Elephant bird",
    "Golden toad",
    "Great auk",
    "Haast's eagle",
    "Japanese sea lion",
    "Javan tiger",
    "Labrador duck",
    "Moa",
    "Passenger pigeon",
    "Pterosaurs",
    "Saber-toothed cat",
    "Schomburgk's deer",
    "Short-faced bear",
    "Steller's sea cow",
    "Thylacine",
    "Toolache wallaby",
    "Western black rhinoceros",
    "Woolly mammoth",
    "Woolly rhinoceros",
    "Barbary lion",
    "Catarina pupfish",
    "Hawaiian crow",
    "Scimitar oryx",
    "Socorro dove",
    "Wyoming toad"
]
